apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend_var.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend_var.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend_var.deployment.app }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.frontend_var.deployment.nodegroupKey }}
                operator: In
                values:
                - {{ .Values.frontend_var.deployment.nodegroupValues }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Values.frontend_var.deployment.container.name }}
          image: {{ .Values.frontend_var.deployment.container.image }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend_var.deployment.configmap.name }}
          imagePullPolicy: Always

